name:                treestate
version:             0.1.0.0
github:              "lgastako/treestate"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2019 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

description:         README at <https://github.com/lgastako/treestate#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- criterion
- lens
- mtl

library:
  source-dirs: src

executables:
  treestate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treestate

tests:
  treestate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treestate
